using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManagerScript : MonoBehaviour {

    //global variables
    private double playerScore;                    //the player's current score
    private double autoGenScoreIncrease;           //the amount score is increased when the autogenerated score increase runs
    private int clickScoreIncrease;             //the amount score is increased on a click event
    private int ticker;                       //incremented by 1 every frame, when larger than autoGenScoreRate reset it to 0 and increase score by autoGenScoreIncrease
    private static int ticksPerSecond = 60;   //amount of ticks in 1 second

    //getters and setters
    public double PlayerScore
    {
        get { return System.Math.Floor(playerScore); }
    }

    // Use this for initialization
    void Start () {
        //initialize Game Manager's variables
        playerScore = 0;
        autoGenScoreIncrease = 0;
        clickScoreIncrease = 0;
        ticker = 0;
	}
	
	// Update is called once per frame
	void Update () {
        //increment ticker
        ticker++;

        //if a second has passed, increase score by autogen amount
        if (ticker % ticksPerSecond == 0)
        {
            AutoGenScore();
        }

	}

    //increase player's score by the autoGenScoreIncrease value
    private void AutoGenScore()
    {
        playerScore += autoGenScoreIncrease;
    }

    //increase player's score by the clickScoreIncrease value
    public void ClickScoreIncrease()
    {
        playerScore += clickScoreIncrease;
    }

    //update the autogen increase value with the upgrade value
    public void UpdateAutoGenScoreIncrease(double increaseChange)
    {
        autoGenScoreIncrease += increaseChange;
    }

    //update the click increase value with the upgrade value
    public void UpdateClickScoreIncrease(int increaseChange)
    {
        clickScoreIncrease += increaseChange;
    }

}
