using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GameManagerScript : MonoBehaviour {

    //global variables
    private double playerScore;                   //the player's current score
    public double autoGenScoreIncrease;           //the amount score is increased when the autogenerated score increase runs
    public double clickScoreIncrease;             //the amount score is increased on a click event
    private int ticker;                       //incremented by 1 every frame, when larger than autoGenScoreRate reset it to 0 and increase score by autoGenScoreIncrease
    private static int ticksPerSecond = 60;   //amount of ticks in 1 second

    //text display score
    public Text objText;

    //Lists referencing the manager class for each upgrade
    public List<PerSecondUpgrade> perSecUpgrades = new List<PerSecondUpgrade>();    //upgrades that increment score every second
    public List<ClickUpgrade> clickUpgrades = new List<ClickUpgrade>();             //upgrades that increment score every click

    //flags for updating score values
    public bool autoGenFlag = false;
    public bool clickFlag = false;

    //getters and setters
    public double PlayerScore
    {
        get { return System.Math.Floor(playerScore); }
        set { playerScore = value; }
    }

    // Use this for initialization
    void Start () {
        //initialize Game Manager's variables
        playerScore = 0;
        ticker = 0;
        //autoGenScoreIncrease = 0;
        //clickScoreIncrease = 0;
	}
	
	// Update is called once per frame
	void Update () {
        //increment tickers
        ticker++;

        //display player score
        objText.text = System.Math.Floor(playerScore).ToString();

        //update click score if new upgrades were bought
        if (clickFlag)
        {
            clickScoreIncrease = 1;

            foreach (ClickUpgrade c in clickUpgrades)
            {
                clickScoreIncrease += c.GetValue();
            }

            clickFlag = false;
        }

        //if a second has passed, increase score by autogen amount
        if (ticker % ticksPerSecond == 0)
        {
            UpdateAutoGenScore();
        }
	}

    //increase player's score by the autoGenScoreIncrease value
    private void UpdateAutoGenScore()
    {
        if(autoGenFlag)
        {
            autoGenScoreIncrease = 0;

            foreach (PerSecondUpgrade p in perSecUpgrades)
            {
                autoGenScoreIncrease += p.GetValue();
            }

            autoGenFlag = false;
        }

        playerScore += autoGenScoreIncrease;
    }

    //decrease player score for whatever reason.
    public void DecreaseScore(double decVal)
    {
        playerScore -= decVal;
    }

    //increase player's score by the clickScoreIncrease value
    public void ClickScoreIncrease()
    {
        playerScore += clickScoreIncrease;
    }
}
