using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GameManagerScript : MonoBehaviour {

    //global variables
    private double playerScore;                   //the player's current score
    public double autoGenScoreIncrease;           //the amount score is increased when the autogenerated score increase runs
    public int clickScoreIncrease;                //the amount score is increased on a click event
    private int autoGenTicker;                    //incremented by 1 every frame, when when a multiple of ticksPerSecond increase score by autoGenScoreIncrease
    private static int ticksPerSecond = 60;       //amount of ticks in 1 second

    //text display score
    public Text objText;

    //getters and setters
    public double PlayerScore
    {
        get { return System.Math.Floor(playerScore); }
        set { playerScore = value; }
    }

    // Use this for initialization
    void Start () {
        //initialize Game Manager's variables
        playerScore = 0;
        //autoGenScoreIncrease = 0;
        //clickScoreIncrease = 0;
        autoGenTicker = 0;
	}
	
	// Update is called once per frame
	void Update () {
        //increment tickers
        autoGenTicker++;

        //display player score
        objText.text = System.Math.Floor(playerScore).ToString();

        //if a second has passed, increase score by autogen amount
        if (autoGenTicker % ticksPerSecond == 0)
        {
            UpdateAutoGenScore();
        }
	}

    //increase player's score by the autoGenScoreIncrease value
    private void UpdateAutoGenScore()
    {
        playerScore += autoGenScoreIncrease;
    }

    //increase player's score by the clickScoreIncrease value
    public void UpdateClickScoreIncrease()
    {
        playerScore += clickScoreIncrease;
    }

    //update the autogen increase value with the upgrade value
    public void UpgradeAutoGenScoreIncrease(double increaseChange)
    {
        autoGenScoreIncrease += increaseChange;
    }

    //update the click increase value with the upgrade value
    public void UpgradeClickScoreIncrease(int increaseChange)
    {
        clickScoreIncrease += increaseChange;
    }
}
