using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GameManagerScript : MonoBehaviour {

    //global variables
    private double playerScore;                    //the player's current score
    public double autoGenScoreIncrease;           //the amount score is increased when the autogenerated score increase runs
    public int clickScoreIncrease;             //the amount score is increased on a click event
    private int ticker;                       //incremented by 1 every frame, when larger than autoGenScoreRate reset it to 0 and increase score by autoGenScoreIncrease
    private static int ticksPerSecond = 60;   //amount of ticks in 1 second

    //text display score
    public Text objText;
    public UpgradeScript[] upgrades = new UpgradeScript[2];

    //getters and setters
    public double PlayerScore
    {
        get { return System.Math.Floor(playerScore); }
    }

    // Use this for initialization
    void Start () {
        //initialize Game Manager's variables
        playerScore = 0;
        ticker = 0;
	}
	
	// Update is called once per frame
	void Update () {
        //increment ticker
        ticker++;
        objText.text = playerScore.ToString();
        //if a second has passed, increase score by autogen amount
        if (ticker % ticksPerSecond == 0)
        {
            AutoGenScore();
        }

	}

    //increase player's score by the autoGenScoreIncrease value
    private void AutoGenScore()
    {
        autoGenScoreIncrease = upgrades[1].SendValue();

        playerScore += autoGenScoreIncrease;
    }

    //increase player's score by the clickScoreIncrease value
    public void ClickScoreIncrease()
    {
        clickScoreIncrease = (int)upgrades[0].SendValue() + 5;

        playerScore += clickScoreIncrease;
    }

    //update the autogen increase value with the upgrade value
    public void UpdateAutoGenScoreIncrease(double increaseChange)
    {
        //autoGenScoreIncrease += increaseChange;
    }

    //update the click increase value with the upgrade value
    public void UpdateClickScoreIncrease(int increaseChange)
    {
        //clickScoreIncrease += increaseChange;
    }

}
